providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:debian-1721088222'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'true'
[phases.build]
dependsOn = ['install']
cmds = ['yarn run build']
cacheDirectories = [
    '.next/cache',
    'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = ['yarn install --frozen-lockfile']
cacheDirectories = ['/usr/local/share/.cache/yarn/v6']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_20',
    'yarn-1_x',
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'bdd2f439c62aa0b8aa97f5c784a965c23f968fe6'

[start]
cmd = 'yarn run start'

